### ISSUE TITLE
Fail to compile on MacOS

### ISSUE THREAD

**Issue by czha168** [Danial-Alh/fast-bleu#2]
I tried to build the package using either gcc or g++, same error:
```
    for (pair<string, int> const &p : counts)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
fast_bleu/cpp_sources/sources/nltk.cpp:102:28: error: variable-sized object may
      not be initialized
    long long p_numerators[max_n] = {0};   // Key = ngram order, and val...
                           ^~~~~
fast_bleu/cpp_sources/sources/nltk.cpp:103:30: error: variable-sized object may
      not be initialized
    long long p_denominators[max_n] = {0}; // Key = ngram order, and val...
                             ^~~~~
```
2 warnings and 2 errors generated.

**Comment by Danial-Alh** [comment]
Thanks for the issue.

What is the g++ version?

**Comment by Danial-Alh** [comment]
Thanks for the issue.

I created a new branch `macos-compile` and resolved the variable-sized object initialization errors. 
As I'm running on Linux, could you please fetch it and check if the `test_cases.py` file runs without error?
