### ISSUE TITLE
Bugs: Fail to calulate BLEU when reference corpus is large

### ISSUE THREAD

**Issue by StevenTang1998** [Danial-Alh/fast-bleu#3]
This is the code to cause problems:
```python
from fast_bleu import BLEU

bleu = BLEU(reference_corpus, weights)
```
when reference_corpus is a list containing 70000 sentences with a length of 200.

And the error message is shown as follows:
```bash
Fatal Python error: Segmentation fault

Thread 0x00007fa775d6a700 (most recent call first):
  File "/home/tangtianyi/anaconda3/lib/python3.7/threading.py", line 300 in wait
  File "/home/tangtianyi/anaconda3/lib/python3.7/threading.py", line 552 in wait
  File "/home/tangtianyi/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 59 in run
  File "/home/tangtianyi/anaconda3/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/home/tangtianyi/anaconda3/lib/python3.7/threading.py", line 890 in _bootstrap

Current thread 0x00007fa809c26700 (most recent call first):
  File "/home/tangtianyi/anaconda3/lib/python3.7/site-packages/fast_bleu/__python_wrapper.py", line 86 in __init__
```

Thank you for taking the time to solve the issues.

**Comment by Danial-Alh** [comment]
can you give more information about the dataset you are using and put some sample of it here?
I duplicated my dataset to have 1.5 million samples, each of them having 10 words  on average and didn't have problem.

**Comment by StevenTang1998** [comment]
For example, `reference_corpus = [[str(i) + str(j) for i in range(100)] for j in range(70000)]`.

**Comment by StevenTang1998** [comment]
I guess maybe it is caused by vocabulary size.
If using `reference_corpus = [['a' for i in range(100)] for j in range(70000)]`, it works.

**Comment by Danial-Alh** [comment]
Yes your guess is close. 
I tested your example without issue but the big vocabulary caused large amount of memory consumption.

Does your memory have enough capacity?

**Comment by StevenTang1998** [comment]
Yes, I am running this code on a server with 256GB memory. And the above code occupied about 3GB memory when failing. I guess  maybe this issue due to the limit memory of local variables in functions.

**Comment by Danial-Alh** [comment]
Excuse me, waht is your OS , `fast_bleu` and python version?

Is the code you are running exactly like this?
> ```python
> from fast_bleu import BLEU
> 
> bleu = BLEU(reference_corpus, weights)
> ```
As I see in you stack trace, there is something about threading.
If you you are using it in mult-ithreaded mode, could you please test it in standard and single-thread mode?

**Comment by StevenTang1998** [comment]
I have tested in three severs, and met the same error.
OS: Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-193-generic x86_64), Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-120-generic x86_64), Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-121-generic x86_64)
Memory: 256GB, 128GB, 64GB
Python: 3.7.4, 3.7.4, 3.7.7
fast_bleu: 0.0.86, 0.0.86, 0.0.86

The entire code is shown as follows, without using multi-threading:
```python
from fast_bleu import BLEU

reference_corpus = [[str(i) + str(j) for i in range(100)] for j in range(70000)]
weight = {'4': (.25, .25, .25, .25)}
BLEU(reference_corpus, weight)
```

**Comment by StevenTang1998** [comment]
Thanks for your help. Now it can run successfully on my server with GCC version 7.5.0.
However, when I installed it on the server with GCC version 5.4.0, it failed to install. Could you lower the barrier to version for more widely usage.

**Comment by Danial-Alh** [comment]
I created a new branch `gcc-downgrade` and lowered compilation flag to c++11. 
I tested it and it seems there is no issue. 

Could you please clone the repo and and test whether the `gcc-downgrade` branch works well or not?
Please uninstall the currently installed version and install the new version with `python setup.py install` command .

**Comment by StevenTang1998** [comment]
I can run it successfully with GCC version 5.4.0. Thank you very much for your help.

Best wishes!
